# Generated by Django 4.0.3 on 2022-03-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookMyRoomApp', '0002_alter_hotels_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
