# Generated by Django 4.0.3 on 2022-03-12 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookMyRoomApp', '0003_alter_guest_id_alter_hotels_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='name',
            new_name='guest_name',
        ),
        migrations.RenameField(
            model_name='hotels',
            old_name='available',
            new_name='availability',
        ),
        migrations.RenameField(
            model_name='hotels',
            old_name='name',
            new_name='hotel_name',
        ),
    ]
