# Generated by Django 4.0.3 on 2022-03-12 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookMyRoomApp', '0004_rename_name_guest_guest_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.CharField(max_length=200)),
                ('checkout', models.CharField(max_length=200)),
            ],
        ),
    ]
