# Generated by Django 4.0.3 on 2022-03-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookMyRoomApp', '0005_reserve'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reserve',
        ),
        migrations.AlterField(
            model_name='guest',
            name='gender',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='guest_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
