# Generated by Django 4.0.3 on 2022-03-13 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookMyRoomApp', '0006_delete_reserve_alter_guest_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.CharField(max_length=200)),
                ('checkout', models.CharField(max_length=200)),
                ('guests_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMyRoomApp.guest')),
                ('hotel_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMyRoomApp.hotels')),
            ],
        ),
    ]
