# Generated by Django 4.0.3 on 2022-03-13 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookMyRoomApp', '0009_delete_hotelslist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='guests_list',
        ),
        migrations.AddField(
            model_name='guest',
            name='reserve',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BookMyRoomApp.reserve'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='hotel_name',
            field=models.CharField(max_length=200),
        ),
    ]
