# Generated by Django 4.0.3 on 2022-03-14 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookMyRoomApp', '0010_remove_reserve_guests_list_guest_reserve_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='hotel_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMyRoomApp.hotels'),
        ),
    ]
