# Generated by Django 4.0.3 on 2022-03-14 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookMyRoomApp', '0011_alter_reserve_hotel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserve',
            old_name='hotel_name',
            new_name='hotel_name1',
        ),
    ]
