# Generated by Django 4.0.3 on 2022-03-14 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookMyRoomApp', '0013_rename_hotel_name1_reserve_hotel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='reserve',
        ),
        migrations.DeleteModel(
            name='Reserve',
        ),
    ]
